[workspace]
authors = ["Justus Magin <keewis@posteo.de>"]
channels = ["conda-forge"]
name = "tools-inventory"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
sphinx = ">=8.3.0,<9"
sphinx-book-theme = ">=1.1.4,<2"
myst-nb = ">=1.3.0,<2"
myst-parser = ">=4.0.1,<5"
python = "3.13.*"
sphinx-design = ">=0.6.1,<0.7"
sphinx-copybutton = ">=0.5.2,<0.6"
sphinx-codeautolink = ">=0.17.5,<0.18"
sphinx-remove-toctrees = ">=1.0.0.post1,<2"
sphinxext-opengraph = ">=0.13.0,<0.14"
healpix-geo = ">=0.0.6,<0.0.7"
xdggs = ">=0.2.2,<0.3"

[feature.dev.dependencies]
jupyterlab = "*"
jupyter-resource-usage = "*"
jupyterlab_code_formatter = "*"
black = "*"
isort = "*"
sphinx-autobuild = ">=2024.10.3,<2025"

[feature.dev.tasks]
sphinx-autobuild = { cmd = "sphinx-autobuild -b html -W -n --open-browser . _build", cwd = "docs" }

[environments]
dev = ["dev"]
