[workspace]
authors = ["Justus Magin <keewis@posteo.de>"]
channels = ["conda-forge"]
name = "tools-inventory"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
sphinx = ">=8.3.0,<9"
sphinx-book-theme = ">=1.1.4,<2"
myst-nb = ">=1.3.0,<2"
myst-parser = ">=4.0.1,<5"
python = "3.13.*"
sphinx-design = ">=0.6.1,<0.7"
sphinx-copybutton = ">=0.5.2,<0.6"
sphinx-codeautolink = ">=0.17.5,<0.18"
